[features]
seeds = false
skip-lint = false

[programs.localnet]
betting_program = "9sJX93ToaYQArDSy24xeWJkJvQhP4r2qRNw7qTabWnDk"

[programs.devnet]
betting_program = "9sJX93ToaYQArDSy24xeWJkJvQhP4r2qRNw7qTabWnDk"

[programs.testnet]
betting_program = "9sJX93ToaYQArDSy24xeWJkJvQhP4r2qRNw7qTabWnDk"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/xyz/solana/betting-program/deploy-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 'tests/**/*.ts'"